table Atualização
	lineageTag: 97083de0-6b87-4072-adb9-bece93e60d45

	measure 'Campo completo' = "ATUALIZADO EM: " & SELECTEDVALUE('Atualização'[Última Atualização])
		lineageTag: 2ad09501-0e89-4653-83fb-d22c0282d86a

	column 'Última Atualização'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8009a1ca-9ec2-4186-9b33-d79cfe49b6ee
		summarizeBy: none
		sourceColumn: Última Atualização

		variation Variation
			isDefault
			relationship: a5e906d3-b7af-41dc-b635-bfcdceb1c921
			defaultHierarchy: LocalDateTable_8dbea108-b7a3-469d-95e0-d307a5c65791.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Atualização = m
		mode: import
		source =
				let
				    Fonte = DateTimeZone.SwitchZone(DateTimeZone.LocalNow(), -3),
				    #"Convertido para Tabela" = #table(1, {{Fonte}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Última Atualização"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Última Atualização", type datetimezone}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

