table Medidas
	lineageTag: 681ecb76-1407-48a4-bd56-82e0fe91324d

	measure 'Top 3 - (Menor Preço)' = ```
			
			    VAR BANDEIRA = [Top 3 - Bandeira]
			    VAR N_cid = COUNT(fat_notas[cidade])
			    
			    VAR VlrMR = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    VAR VlrCid = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    RETURN COALESCE(IF(N_cid>1, VlrMR, VlrCid),"-")
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Top Preço
		lineageTag: ce0fc33e-61c7-4a63-91a8-f644f194f0e5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Top 1 - (Menor Preço)' = ```
			
			    VAR BANDEIRA = [Top 1 - Bandeira]
			    VAR N_cid = COUNT(fat_notas[cidade])
			    
			    VAR VlrMR = CALCULATE(
			                        MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    VAR VlrCid = CALCULATE(
			                        MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    RETURN COALESCE(IF(N_cid>1, VlrMR, VlrCid),"-") 
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Top Preço
		lineageTag: c63c8c8b-c570-4120-acb3-5d82a0373956

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Top 4 - (Menor Preço)' = ```
			
			    VAR BANDEIRA = [Top 4 - Bandeira]
			    VAR N_cid = COUNT(fat_notas[cidade])
			    
			    VAR VlrMR = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    VAR VlrCid = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    RETURN COALESCE(IF(N_cid>1, VlrMR, VlrCid),"-")
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Top Preço
		lineageTag: da586273-7da2-451c-aedd-2bb95a196848

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Top 5 - (Menor Preço)' = ```
			
			    VAR BANDEIRA = [Top 5 - Bandeira]
			    VAR N_cid = COUNT(fat_notas[cidade])
			    
			    VAR VlrMR = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    VAR VlrCid = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    RETURN COALESCE(IF(N_cid>1, VlrMR, VlrCid),"-")
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Top Preço
		lineageTag: f1763947-5337-4461-acbc-45d0716fc0b3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Top 6 - (Menor Preço)' = ```
			
			    VAR BANDEIRA = [Top 6 - Bandeira]
			    VAR N_cid = COUNT(fat_notas[cidade])
			    
			    VAR VlrMR = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    VAR VlrCid = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    RETURN COALESCE(IF(N_cid>1, VlrMR, VlrCid),"-")
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Top Preço
		lineageTag: 2044de95-a556-4313-b524-ef527ec00484

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Top 2 - (Menor Preço)' = ```
			
			    VAR BANDEIRA = [Top 2 - Bandeira]
			    VAR N_cid = COUNT(fat_notas[cidade])
			    
			    VAR VlrMR = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    VAR VlrCid = CALCULATE(
			                      MIN(fat_notas[valor]),
			                        FILTER(fat_notas, fat_notas[bandeira] = BANDEIRA),
			                        ALLEXCEPT(fat_notas, fat_notas[PRODUTO])
			                    )
			    RETURN COALESCE(IF(N_cid>1, VlrMR, VlrCid),"-")
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Top Preço
		lineageTag: 969c8a24-9a7f-46a2-8c3e-080ed1e2cf15

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Drogamais (Menor Preço)' = COALESCE(CALCULATE(MIN(fat_notas[valor]), fat_notas[bandeira] = "DROGAMAIS"),"-")
		displayFolder: Top Preço
		lineageTag: 2ea7d78b-047d-4a20-bc90-e4891c55a2bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top 1 (Última Compra)' = ```
			
			VAR nBANDEIRA = [Top 1 - Bandeira] 
			
			RETURN 
			    COALESCE( 
			        CALCULATE( 
			            MAX(fat_notas[date]), 
			            fat_notas[Bandeira] = nBANDEIRA
			            ), "-" 
			        )
			```
		formatString: General date
		displayFolder: Última Compra
		lineageTag: 7d96e3d3-970d-4470-a8d2-03e5b882ccf1

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Top 2 (Última Compra)' = ```
			
			
			VAR nBANDEIRA = [Top 2 - Bandeira]
			
			RETURN
			    COALESCE(
			        CALCULATE(
			            MAX(fat_notas[date]),
			                fat_notas[Bandeira] = nBANDEIRA
			        ), 
			        "-"
			    )
			```
		formatString: General Date
		displayFolder: Última Compra
		lineageTag: ac2e8990-1206-4153-bdbc-83e69a13d284

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Top 3 (Última Compra)' = ```
			
			
			VAR nBANDEIRA = [Top 3 - Bandeira]
			
			RETURN
			    COALESCE(
			        CALCULATE(
			            MAX(fat_notas[date]), 
			                fat_notas[Bandeira] = nBANDEIRA
			        ), 
			        "-"
			    )
			```
		formatString: General Date
		displayFolder: Última Compra
		lineageTag: e0746651-5977-4fbe-b905-79335778361f

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Top 4 (Última Compra)' = ```
			
			
			VAR nBANDEIRA = [Top 4 - Bandeira]
			
			RETURN
			    COALESCE(
			        CALCULATE(
			            MAX(fat_notas[date]),
			                fat_notas[Bandeira] = nBANDEIRA
			        ), 
			        "-"
			    )
			```
		formatString: General Date
		displayFolder: Última Compra
		lineageTag: c7131d95-e616-4c94-8ac6-48b96023ce68

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Top 5 (Última Compra)' = ```
			
			
			VAR nBANDEIRA = [Top 5 - Bandeira]
			
			RETURN
			    COALESCE(
			        CALCULATE(
			            MAX(fat_notas[date]), 
			            fat_notas[Bandeira] = nBANDEIRA
			        ), 
			        "-"
			    )
			```
		formatString: General Date
		displayFolder: Última Compra
		lineageTag: c13be306-586c-4264-9557-2d485df725fa

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Top 6 (Última Compra)' = ```
			
			
			VAR nBANDEIRA = [Top 6 - Bandeira]
			
			RETURN
			    COALESCE(
			        CALCULATE(
			            MAX(fat_notas[date]),
			            fat_notas[Bandeira] = nBANDEIRA
			        ), 
			        "-"
			    )
			```
		formatString: General Date
		displayFolder: Última Compra
		lineageTag: b48059ce-9a25-4598-9297-95f7ae739f19

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Drogamais (Última Compra)' = ```
			COALESCE(CALCULATE(MAX(fat_notas[date]),dim_logos[bandeira] = "DROGAMAIS"),"-") 
			```
		formatString: General Date
		displayFolder: Última Compra
		lineageTag: 1bc33c58-9c5e-4868-add0-684437e147a7

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Qtd. Cidades' = DISTINCTCOUNT(fat_notas[geohash])
		formatString: 0
		displayFolder: Quantidades
		lineageTag: 0d3e46eb-2923-4b6b-ab32-55d6e98bcffc

	measure 'Qtd. Bandeiras' = DISTINCTCOUNT(fat_notas[bandeira])
		formatString: 0
		displayFolder: Quantidades
		lineageTag: 70471531-f3ef-4fb8-b287-e6dc00ed1fa5

	measure 'Qtd. Razão Social' = DISTINCTCOUNT(fat_notas[id_loja])
		formatString: 0
		displayFolder: Quantidades
		lineageTag: e5569aeb-cd23-4fa7-82ed-53357b75c9c8

	measure 'Top 1 - Bandeira' = ```
			
			
			    VAR N_cid = DISTINCTCOUNT(fat_notas[cidade])
			    VAR Microrregiao = SELECTEDVALUE(fat_notas[microrregiao])
			    VAR Geohash = SELECTEDVALUE(fat_notas[geohash])
			
			    VAR BanMR = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_microrregiao] = 1,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[Microrregiao] = Microrregiao
			                        )
			                    )
			    VAR BanCid = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_cidade] = 1,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[geohash] = Geohash
			                        )
			                    )
			    RETURN COALESCE(IF(N_cid>1, BanMR, BanCid),"-")
			```
		displayFolder: Bandeiras
		lineageTag: 214deae1-665b-44bc-b3c6-61b196f11245

	measure 'Top 2 - Bandeira' = ```
			
			
			    VAR N_cid = DISTINCTCOUNT(fat_notas[cidade])
			    VAR Microrregiao = SELECTEDVALUE(fat_notas[microrregiao])
			    VAR Geohash = SELECTEDVALUE(fat_notas[geohash])
			
			    VAR BanMR = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_microrregiao] = 2,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[Microrregiao] = Microrregiao
			                        )
			                    )
			    VAR BanCid = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_cidade] = 2,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[geohash] = Geohash
			                        )
			                    )
			    RETURN COALESCE(IF(N_cid>1, BanMR, BanCid),"-")
			```
		displayFolder: Bandeiras
		lineageTag: 65c3519d-9515-4878-9228-2a85ab35fe68

	measure 'Top 3 - Bandeira' = ```
			
			
			    VAR N_cid = DISTINCTCOUNT(fat_notas[cidade])
			    VAR Microrregiao = SELECTEDVALUE(fat_notas[microrregiao])
			    VAR Geohash = SELECTEDVALUE(fat_notas[geohash])
			
			    VAR BanMR = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_microrregiao] = 3,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[Microrregiao] = Microrregiao
			                        )
			                    )
			    VAR BanCid = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_cidade] = 3,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[geohash] = Geohash
			                        )
			                    )
			    RETURN COALESCE(IF(N_cid>1, BanMR, BanCid),"-")
			```
		displayFolder: Bandeiras
		lineageTag: 5d9faa06-d716-4d47-86b0-b55743812a99

	measure 'Top 4 - Bandeira' = ```
			
			
			    VAR N_cid = DISTINCTCOUNT(fat_notas[cidade])
			    VAR Microrregiao = SELECTEDVALUE(fat_notas[microrregiao])
			    VAR Geohash = SELECTEDVALUE(fat_notas[geohash])
			
			    VAR BanMR = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_microrregiao] = 4,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[Microrregiao] = Microrregiao
			                        )
			                    )
			    VAR BanCid = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_cidade] = 4,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[geohash] = Geohash
			                        )
			                    )
			    RETURN COALESCE(IF(N_cid>1, BanMR, BanCid),"-")
			```
		displayFolder: Bandeiras
		lineageTag: 1492c869-b17b-4237-aa5f-81e4d480a32e

	measure 'Top 5 - Bandeira' = ```
			
			
			    VAR N_cid = DISTINCTCOUNT(fat_notas[cidade])
			    VAR Microrregiao = SELECTEDVALUE(fat_notas[microrregiao])
			    VAR Geohash = SELECTEDVALUE(fat_notas[geohash])
			
			    VAR BanMR = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_microrregiao] = 5,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[Microrregiao] = Microrregiao
			                        )
			                    )
			    VAR BanCid = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_cidade] = 5,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[geohash] = Geohash
			                        )
			                    )
			    RETURN COALESCE(IF(N_cid>1, BanMR, BanCid),"-")
			```
		displayFolder: Bandeiras
		lineageTag: f598c7f5-f444-4a65-befa-0a241c9b1fc5

	measure 'Top 6 - Bandeira' = ```
			
			
			    VAR N_cid = DISTINCTCOUNT(fat_notas[cidade])
			    VAR Microrregiao = SELECTEDVALUE(fat_notas[microrregiao])
			    VAR Geohash = SELECTEDVALUE(fat_notas[geohash])
			
			    VAR BanMR = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_microrregiao] = 6,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[Microrregiao] = Microrregiao
			                        )
			                    )
			    VAR BanCid = CALCULATE(
			                      SELECTEDVALUE(fat_notas[bandeira]), 
			                        fat_notas[rank_cidade] = 6,
			                        FILTER(
			                            fat_notas,
			                            fat_notas[geohash] = Geohash
			                        )
			                    )
			    RETURN COALESCE(IF(N_cid>1, BanMR, BanCid),"-")
			```
		displayFolder: Bandeiras
		lineageTag: deaace2a-b734-4a26-b6ad-8dd49f50143b

	measure Drogamais = ```
			"DROGAMAIS"
			
			```
		displayFolder: Bandeiras
		lineageTag: bcc0c271-a6ee-4b94-88ea-a0cd99a8ecf5

	measure 'Outras Bandeiras' = "OUTRAS BANDEIRAS"
		displayFolder: Bandeiras
		lineageTag: 2fed4849-4ae4-400a-92dc-09a28fc646d1

	measure 'Texto - Razão Social' = COALESCE(IF(DISTINCTCOUNT(fat_notas[razao_social]) > 1, "NÃO SELECIONADA", SELECTEDVALUE(fat_notas[razao_social])),"NÃO SELECIONADA")
		displayFolder: Razão Social
		lineageTag: e24b2b68-ec76-4b81-82ca-cc72dbc43592

	measure 'Menor Valor - Razão Social' = IF([Texto - Razão Social] = "NÃO SELECIONADA", "-", CALCULATE(MIN(fat_notas[valor])))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Razão Social
		lineageTag: 850b1a86-0933-403d-a923-f2c58e83555b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Qtd Notas - Razão Social' = IF([Texto - Razão Social] = "NÃO SELECIONADA", "-", COUNT(dim_produtos[descricao]))
		displayFolder: Razão Social
		lineageTag: 195c36ee-c082-4cd0-b934-702944cc4c9e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Desconto - Razão Social' = IF([Texto - Razão Social] = "NÃO SELECIONADA", "-", AVERAGE(fat_notas[valor_desconto]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Razão Social
		lineageTag: 6de01c53-326f-4256-8dcc-937f6e36efb4

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Média Valor - Razão Social' = IF([Texto - Razão Social] = "NÃO SELECIONADA", "-", AVERAGE(fat_notas[valor]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Razão Social
		lineageTag: 1833947b-4bae-414b-a0eb-0b8261aa0fae

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'PMC - Razão Social' = IF([Texto - Razão Social] = "NÃO SELECIONADA", "-", SELECTEDVALUE(fat_notas[valor_tabela]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Razão Social
		lineageTag: b4682046-d7f2-4bcb-b0d7-87e60bf2bf85

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Últ. Nota - Razão Social' = IF([Texto - Razão Social] = "NÃO SELECIONADA", "-", FORMAT(MAX(fat_notas[date]), "dd/mm/yyyy hh:mm"))
		formatString: General Date
		displayFolder: Razão Social
		lineageTag: 1b215a04-edca-4c84-a275-79682cd6cf8d

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Qtd Notas' = ```
			
			    COUNTROWS(fat_notas)
			```
		formatString: 0
		displayFolder: Quantidades
		lineageTag: ecf985aa-9453-43f3-bf2c-2bd15abaddf5

	measure 'Outras Bandeiras - Menor Preço' = COALESCE(CALCULATE(MIN(fat_notas[valor]), fat_notas[bandeira] = "OUTRAS BANDEIRAS"),"-")
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Top Preço
		lineageTag: ad8bbe04-d6d0-4b82-8e07-0fa6bea42a9b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Top 1 - Imagem' = ```
			
			    VAR Bandeira =  [Top 1 - Bandeira]
			    
			    RETURN COALESCE(CALCULATE(
			                        SELECTEDVALUE(dim_logos[logo_bandeira]),
			                        dim_logos[bandeira] = Bandeira,
			                        ALLEXCEPT(fat_notas, fat_notas[bandeira], fat_notas[microrregiao], fat_notas[cidade])),
			                    "-")
			```
		displayFolder: Imagens
		lineageTag: 5d39378e-796a-402a-882c-1be2b014a0af

	measure 'Top 2 - Imagem' = ```
			
			    VAR Bandeira =  [Top 2 - Bandeira]
			    
			    RETURN COALESCE(CALCULATE(
			                        SELECTEDVALUE(dim_logos[logo_bandeira]),
			                        dim_logos[bandeira] = Bandeira,
			                        ALLEXCEPT(fat_notas, fat_notas[bandeira], fat_notas[Microrregiao], fat_notas[cidade])),
			                    "-")
			```
		displayFolder: Imagens
		lineageTag: 933bbb25-ee53-40c9-b940-02ceaed812a1

	measure 'Top 3 - Imagem' = ```
			
			                COALESCE(CALCULATE(
			                        SELECTEDVALUE(dim_logos[logo_bandeira]),
			                        FILTER(dim_logos, dim_logos[bandeira] = [Top 3 - Bandeira]),
			                        ALLEXCEPT(fat_notas, fat_notas[Microrregiao], fat_notas[cidade])),
			                    "-")
			```
		displayFolder: Imagens
		lineageTag: ade456b8-30eb-4f2f-b2c2-f187b3737e31

	measure 'Top 4 - Imagem' = ```
			
			    VAR Bandeira =  [Top 4 - Bandeira]
			    
			    RETURN COALESCE(CALCULATE(
			                        SELECTEDVALUE(dim_logos[logo_bandeira]),
			                        dim_logos[bandeira] = Bandeira,
			                        ALLEXCEPT(fat_notas, fat_notas[bandeira], fat_notas[Microrregiao], fat_notas[cidade])),
			                    "-")
			```
		displayFolder: Imagens
		lineageTag: e3e772ea-f827-4609-b263-908192205cd4

	measure 'Top 5 - Imagem' = ```
			
			    VAR Bandeira =  [Top 5 - Bandeira]
			    
			    RETURN COALESCE(CALCULATE(
			                        SELECTEDVALUE(dim_logos[logo_bandeira]),
			                        dim_logos[bandeira] = Bandeira,
			                        ALLEXCEPT(fat_notas, fat_notas[bandeira], fat_notas[Microrregiao], fat_notas[cidade])),
			                    "-")
			```
		displayFolder: Imagens
		lineageTag: 210d370c-849c-4fdd-973a-2de17b171638

	measure 'Top 6 - Imagem' = ```
			
			    VAR Bandeira =  [Top 6 - Bandeira]
			    
			    RETURN COALESCE(CALCULATE(
			                        SELECTEDVALUE(dim_logos[logo_bandeira]),
			                        dim_logos[bandeira] = Bandeira,
			                        ALLEXCEPT(fat_notas, fat_notas[bandeira], fat_notas[Microrregiao], fat_notas[cidade])),
			                    "-")
			```
		displayFolder: Imagens
		lineageTag: 11608620-e0da-4268-ac90-db31858920ee

	measure Moda = ```
			
			
			VAR Tabela = 
			    SUMMARIZE(fat_notas, fat_notas[valor],
			    "QTD", COUNT(fat_notas[gtin])
			    )
			VAR Maximo = MAXX(Tabela, [QTD])
			RETURN COALESCE(MAXX(FILTER(Tabela, [QTD] = Maximo), fat_notas[valor]),AVERAGE(fat_notas[valor]))
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: 502cb3bf-4424-40c9-9bea-444ef447279f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Mediana = COALESCE(MEDIAN(fat_notas[valor]),AVERAGE(fat_notas[valor]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: fd86a17f-cbe5-40da-b8b8-ce93c1f8e538

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Menor Valor' = COALESCE(MIN(fat_notas[valor]),AVERAGE(fat_notas[valor]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: 2c6ec65c-96ac-40af-b342-93a11cc4fae6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Outras Bandeiras (Última Compra)' = ```
			
			
			COALESCE(
			        CALCULATE(
			            MAX(fat_notas[date]), 
			            FILTER(fat_notas, fat_notas[bandeira] = "OUTRAS BANDEIRAS")
			        ), 
			        "-"
			    )
			```
		formatString: General Date
		displayFolder: Última Compra
		lineageTag: b47370e9-a62e-43ce-886e-d07ef1bb4303

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Mediana TXT' = COALESCE(MEDIAN(fat_notas[valor]),"-")
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: 45e552a3-11d3-453e-a016-8448862972cd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Menor Valor TXT' = COALESCE(MIN(fat_notas[valor]),"-")
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: 4bbe0ec9-f78d-4eb6-8a04-ca8b0e62e4f7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Moda TXT' = ```
			
			
			VAR Tabela = 
			    SUMMARIZE(fat_notas, fat_notas[valor],
			    "QTD", COUNT(fat_notas[gtin])
			    )
			VAR Maximo = MAXX(Tabela, [QTD])
			RETURN COALESCE(MAXX(FILTER(Tabela, [QTD] = Maximo), fat_notas[valor]),"-")
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: c3a139e4-e87b-4e69-a2f4-f09d7678d320

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Microrregião_Priorizada =
			
			VAR TabelaContagem =
			    ADDCOLUMNS (
			        VALUES ( fat_notas[microrregiao] ),
			        "@Contagem", CALCULATE ( COUNTROWS ( fat_notas ) )
			    )
			VAR TabelaTop1 =
			    TOPN (
			        1,
			        TabelaContagem,
			        [@Contagem], DESC,                // 1ª Regra: Prioriza pela MAIOR contagem (DESC)
			        fat_notas[microrregiao], ASC // 2ª Regra: Desempata por ordem alfabética (ASC)
			    )
			VAR Resultado =
			    MAXX ( TabelaTop1, fat_notas[microrregiao] ) // Extrai o valor de texto da tabela de 1 linha
			
			RETURN
			    Resultado
		displayFolder: Geral
		lineageTag: d942848e-9fbc-4770-8359-e23978882b11

	measure 'Eixo Max.' =
			
			
			VAR Valor = MAX(fat_notas[valor])
			
			RETURN Valor + Valor*0.10
		displayFolder: Geral
		lineageTag: ed33a668-5ee4-4f90-95ac-6a537fafd2ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eixo Min.' =
			
			
			VAR Valor = MIN(fat_notas[valor])
			
			RETURN Valor - Valor*0.10
		displayFolder: Geral
		lineageTag: fef57a6d-67b0-4fd2-b3a0-ed8c92735b90

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mediana TXT S/OB' = COALESCE(CALCULATE(MEDIAN(fat_notas[valor]), fat_notas[bandeira]<>"Outras Bandeiras"),"-")
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: 3629d8bd-75dc-4ab6-8f55-d5ee4a884e79

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Menor Valor TXT S/OB' = COALESCE(CALCULATE(MIN(fat_notas[valor]), fat_notas[bandeira]<>"Outras Bandeiras"),"-")
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: 113caed7-19cf-4d4b-a39b-1d6d8214cc06

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Moda TXT S/OB' = ```
			
			
			VAR Tabela = 
			    SUMMARIZE(fat_notas, fat_notas[valor],
			    "QTD", COUNT(fat_notas[gtin])
			    )
			VAR Maximo = MAXX(Tabela, [QTD])
			RETURN COALESCE(CALCULATE(MAXX(FILTER(Tabela, [QTD] = Maximo), fat_notas[valor]), fat_notas[bandeira]<>"Outras Bandeiras"),"-")
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: f642bda1-f25c-4030-b534-9fe8e3fee8b5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Mediana S/OB' = COALESCE(CALCULATE(MEDIAN(fat_notas[valor]), fat_notas[bandeira]<>"Outras Bandeiras"),AVERAGE(fat_notas[valor]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: a364fcf7-7ea6-4b80-876d-e73572ffd163

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Menor Valor S/OB' = COALESCE(CALCULATE(MIN(fat_notas[valor]), fat_notas[bandeira]<>"Outras Bandeiras"),AVERAGE(fat_notas[valor]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: dbe06a78-f071-4098-9ef7-d777276d596d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Moda S/OB' = ```
			
			
			VAR Tabela = 
			    SUMMARIZE(fat_notas, fat_notas[valor],
			    "QTD", COUNT(fat_notas[gtin])
			    )
			VAR Maximo = MAXX(Tabela, [QTD])
			RETURN COALESCE(CALCULATE(MAXX(FILTER(Tabela, [QTD] = Maximo), fat_notas[valor]), fat_notas[bandeira] <> "Outras Bandeiras"),AVERAGE(fat_notas[valor]))
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Geral
		lineageTag: 84a98b87-20c5-466f-8d56-8a33aea90061

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Menor Preço 1' = CALCULATE(MIN(fat_notas[valor]), FILTER(fat_notas, fat_notas[bandeira] = [Top 1 - Bandeira]), ALLEXCEPT(fat_notas, fat_notas[microrregiao], fat_notas[cidade], fat_notas[PRODUTO]))
		displayFolder: Geral
		lineageTag: 880f7acf-8606-4fee-8205-3417c3d0030f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Período do Produto' = ```
			"De "& DATEVALUE(SELECTEDVALUE(dim_produtos[data_insercao])) &" á "& DATEVALUE(SELECTEDVALUE(dim_produtos[data_insercao]))+30 
			```
		lineageTag: 6eac3d40-2c03-4f19-b6ae-b25d4aa6127f

	measure DataHoraTexto = FORMAT(SELECTEDVALUE(fat_notas[date]), "dd/MM/yyyy HH:mm:ss")
		displayFolder: Geral
		lineageTag: 50e0ef95-0b04-4396-9a22-8c282b793c48

	measure 'Data Limite' = TODAY()-15
		formatString: Short Date
		lineageTag: bb4d1b11-c940-43b0-8037-ef043ca1da81

	measure 'Media Mercado Desconto' = COALESCE(AVERAGE(fat_notas[valor_desconto]),0)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: f31d5dde-97cc-4c42-b407-922e0b0571de

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '%Media Mercado Desconto' = DIVIDE([Media Mercado Desconto],[Media Mercado PMC],0)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: Desconto
		lineageTag: 1319ffb8-3fe2-40db-bf74-7a772d4e46bd

	measure 'Media Loja Desconto Card' = ```
			
			VAR QtdProdutosSelecionados =
			    CALCULATE(
			        DISTINCTCOUNT(dim_produtos[PRODUTO]),
			        ALLSELECTED(dim_produtos)
			    )
			VAR MediaValor =
			    AVERAGE(view_menorPreco_valor_email[valor_desconto])
			RETURN
			IF(
			    QtdProdutosSelecionados > 1,
			    "-",
			    IF(
			        ISBLANK(MediaValor),
			        "N.E.",
			        MediaValor
			    )
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: b582291a-f350-4ff3-ae6c-76f0fbe7c1cd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '%Media Loja Desconto Card' = ```
			
			VAR QtdProdutosSelecionados =
			    CALCULATE(
			        DISTINCTCOUNT(dim_produtos[PRODUTO]),
			        ALLSELECTED(dim_produtos)
			    )
			
			VAR ValorDesconto = [Media Loja Desconto Card]
			VAR ValorPMC = [Media Loja PMC Card]
			
			-- Quando uma das medidas retornar "Não Encontrado", ela vira BLANK no VAR acima
			VAR ValorDescontoNum =
			    IF(ISNUMBER(ValorDesconto), ValorDesconto)
			VAR ValorPMCNum =
			    IF(ISNUMBER(ValorPMC), ValorPMC)
			
			RETURN
			IF(
			    QtdProdutosSelecionados > 1,
			    "-",
			    IF(
			        OR(ISBLANK(ValorDescontoNum), ISBLANK(ValorPMCNum)),
			        "N.E.",
			        DIVIDE(ValorDescontoNum, ValorPMCNum, 0)
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desconto
		lineageTag: c470c8c1-fe44-41e5-bbdb-e982ee31e7f3

	measure 'Media Loja PMC Card' = ```
			
			VAR QtdProdutosSelecionados =
			    CALCULATE(
			        DISTINCTCOUNT(dim_produtos[PRODUTO]),
			        ALLSELECTED(dim_produtos)
			    )
			VAR MediaValor =
			    AVERAGE(view_menorPreco_valor_email[valor_tabela])
			RETURN
			IF(
			    QtdProdutosSelecionados > 1,
			    "-",
			    IF(
			        ISBLANK(MediaValor),
			        "N.E.",
			        MediaValor
			    )
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: 542141c8-5370-458b-8683-f8f4e6b202fa

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Media Mercado PMC' = COALESCE(AVERAGE(fat_notas[valor_tabela]),0)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: 20934ff1-ff21-4456-889d-6568e43e8932

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure teste = [Media Loja Desconto Card]/[Media Loja PMC Card]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Geral
		lineageTag: 64f02ae2-f62d-45bb-b2d6-ae7723eea26f

	measure 'Media Mercado PMC Card' = ```
			
			VAR QtdProdutosSelecionados =
			    CALCULATE(
			        DISTINCTCOUNT(dim_produtos[PRODUTO]),
			        ALLSELECTED(dim_produtos)
			    )
			RETURN
			IF(
			    QtdProdutosSelecionados > 1,
			    "-",
			    COALESCE(AVERAGE(fat_notas[valor_tabela]), 0)
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: 37ba9695-6298-4c62-a86f-bec0d922a0d3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Media Mercado Desconto Card' = ```
			
			VAR QtdProdutosSelecionados =
			    CALCULATE(
			        DISTINCTCOUNT(dim_produtos[PRODUTO]),
			        ALLSELECTED(dim_produtos)
			    )
			RETURN
			IF(
			    QtdProdutosSelecionados > 1,
			    "-",
			    COALESCE(AVERAGE(fat_notas[valor_desconto]), 0)
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: 98152a50-769d-4bf6-a507-183dd93500ce

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '%Media Mercado Desconto Card' = ```
			
			IF(
			    NOT HASONEVALUE(dim_produtos[PRODUTO]),
			    "-",
			    DIVIDE([Media Mercado Desconto], [Media Mercado PMC], 0)
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desconto
		lineageTag: b9a10d28-d569-4599-8384-8204a85eebea

	measure 'Media Loja PMC' = ```
			
			VAR MediaValor =
			    AVERAGE(view_menorPreco_valor_email[valor_tabela])
			RETURN
			IF(
			    ISBLANK(MediaValor),
			    "Não Encontrado",
			    MediaValor
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: 0371a19f-6f97-494b-a294-f30ea8706a7c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Media Loja Desconto' = ```
			
			VAR MediaValor =
			    AVERAGE(view_menorPreco_valor_email[valor_desconto])
			RETURN
			IF(
			    ISBLANK(MediaValor),
			    "Não Encontrado",
			    MediaValor
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: f7492392-603a-461e-8c59-2e682d3198a5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '%Media Loja Desconto' = ```
			
			VAR Desconto = [Media Loja Desconto]
			VAR PMC = [Media Loja PMC]
			
			VAR DescontoNum =
			    IF(ISNUMBER(Desconto), Desconto)
			
			VAR PMCNum =
			    IF(ISNUMBER(PMC), PMC)
			
			RETURN
			IF(
			    OR(ISBLANK(DescontoNum), ISBLANK(PMCNum)),
			    "Não Encontrado",
			    DIVIDE(DescontoNum, PMCNum, 0)
			)
			
			```
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: Desconto
		lineageTag: 2f3657c9-8571-44ac-98fc-249ecaec6bfb

	measure 'Media Mercado Final Card' = ```
			
			VAR QtdProdutosSelecionados =
			    CALCULATE(
			        DISTINCTCOUNT(dim_produtos[PRODUTO]),
			        ALLSELECTED(dim_produtos)
			    )
			RETURN
			IF(
			    QtdProdutosSelecionados > 1,
			    "-",
			    COALESCE(AVERAGE(fat_notas[valor]), 0)
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: 10adbb5f-9397-44f7-b145-3e9031a9f3b0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Media Loja Final Card' = ```
			
			VAR QtdProdutosSelecionados =
			    CALCULATE(
			        DISTINCTCOUNT(dim_produtos[PRODUTO]),
			        ALLSELECTED(dim_produtos)
			    )
			VAR MediaValor =
			    AVERAGE(view_menorPreco_valor_email[valor])
			RETURN
			IF(
			    QtdProdutosSelecionados > 1,
			    "-",
			    IF(
			        ISBLANK(MediaValor),
			        "N.E.",
			        MediaValor
			    )
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: 63d21185-0348-4bff-aeea-4b610cf804ff

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Media Loja Final' = ```
			
			VAR MediaValor =
			    AVERAGE(view_menorPreco_valor_email[valor])
			RETURN
			IF(
			    ISBLANK(MediaValor),
			    "Não Encontrado",
			    MediaValor
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Desconto
		lineageTag: 0998e6da-21b9-4e4e-afbf-2672edd6a007

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Media Mercado Final' = COALESCE(AVERAGE(fat_notas[valor]),0)
		displayFolder: Desconto
		lineageTag: 3d75bc14-cac0-487a-8a39-00263397d95f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		lineageTag: a8645c25-14d8-4a4f-8fd8-48c76b085d6b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = e39562f48d3b401097d718afdea9e0a7

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

